import { PersistentLevelDefinition } from "../puzzle.types";
import { EffectScope, FlowCombineStrategy, LinkDirection } from "./effects.models";

export enum EffectPlaygroundScenario { GEM_EFFECTS = "GEM_EFFECTS", ALL_GEM_EFFECTS = "ALL_GEM_EFFECTS", GEM_EFFECT_COMBINATIONS = "GEM_EFFECT_COMBINATIONS", ELEMENTAL_BARRIERS = "ELEMENTAL_BARRIERS", WALL_WITH_FOLLOW_UP_EFFECTS = "WALL_WITH_FOLLOW_UP_EFFECTS", LINK_EFFECTS = "LINK_EFFECTS", CHAIN_LOCK = "CHAIN_LOCK", CHAIN_WITH_AREA = "CHAIN_WITH_AREA", LINK_GEM_SEQUENCE = "LINK_GEM_SEQUENCE", LINK_AREA_SEQUENCE = "LINK_AREA_SEQUENCE", LINK_MIXED_CASCADE = "LINK_MIXED_CASCADE", AREA_EFFECTS = "AREA_EFFECTS", ALL_AREA_EFFECTS = "ALL_AREA_EFFECTS", FLOW_BRANCHING = "FLOW_BRANCHING", FLOW_CONVERGENCE = "FLOW_CONVERGENCE", FLOW_CYCLE = "FLOW_CYCLE", ALL_EFFECTS = "ALL_EFFECTS" }
/** First selector in the playground. Each group owns focused scenarios and cross-effect combinations. */
export enum EffectPlaygroundGroup { GEM = "GEM", LINK = "LINK", AREA = "AREA", FLOW = "FLOW", COMPLETE = "COMPLETE" }
const level = (scenario: EffectPlaygroundScenario, outerValues: number[], innerValues: PersistentLevelDefinition["innerValues"], effects: NonNullable<PersistentLevelDefinition["effectConfiguration"]>["effects"], flowRules?: NonNullable<PersistentLevelDefinition["effectConfiguration"]>["flowRules"]): PersistentLevelDefinition => ({ id: `effect-playground-${scenario.toLowerCase()}`, number: 1, title: `Effect Playground · ${scenario}`, schemaVersion: 1, variant: "persistent", positions: outerValues.length, initialRotation: 0, outerValues, innerValues, slotPhases: outerValues.map((_, outerIndex) => [{ outerIndex }]), effectConfiguration: { enabled: true, effects, flowRules } });

export const EFFECT_PLAYGROUND_SCENARIOS: Readonly<Record<EffectPlaygroundScenario, PersistentLevelDefinition>> = {
  [EffectPlaygroundScenario.GEM_EFFECTS]: level(EffectPlaygroundScenario.GEM_EFFECTS, [8, -6, 4, -8, 5, -3], [-2, 2, -2, 2, -1, 1], [{ preset: "SHIELD_2", target: { type: EffectScope.GEM, gemIndex: 0 } }, { preset: "WALL_3", target: { type: EffectScope.GEM, gemIndex: 1 } }, { preset: "MIRROR_1", target: { type: EffectScope.GEM, gemIndex: 2 } }]),
  [EffectPlaygroundScenario.ELEMENTAL_BARRIERS]: { ...level(EffectPlaygroundScenario.ELEMENTAL_BARRIERS, [6, 6, 6, 6, 6, 6], [-2, -2, -2, -2, -2, -2], [{ preset: "ICE_2", target: { type: EffectScope.GEM, gemIndex: 0 } }, { preset: "FIRE_2", target: { type: EffectScope.GEM, gemIndex: 1 } }, { preset: "ICE_2", target: { type: EffectScope.GEM, gemIndex: 2 } }, { preset: "FIRE_2", target: { type: EffectScope.GEM, gemIndex: 3 } }]), innerElements: ["fire", "ice", "ice", "fire", null, null] },
  [EffectPlaygroundScenario.ALL_GEM_EFFECTS]: level(EffectPlaygroundScenario.ALL_GEM_EFFECTS, [8, -6, 4, -5, 7, -8, 3, -4, 6], [-2, 2, -2, 2, -2, 2, -1, 1, -2], [{ preset: "SHIELD_2", target: { type: EffectScope.GEM, gemIndex: 0 } }, { preset: "WALL_3", target: { type: EffectScope.GEM, gemIndex: 1 } }, { preset: "MIRROR_1", target: { type: EffectScope.GEM, gemIndex: 2 } }, { preset: "AMPLIFIER_X2", target: { type: EffectScope.GEM, gemIndex: 3 } }, { preset: "INVERTER_1", target: { type: EffectScope.GEM, gemIndex: 4 } }, { preset: "ICE_2", target: { type: EffectScope.GEM, gemIndex: 5 } }, { preset: "FIRE_2", target: { type: EffectScope.GEM, gemIndex: 6 } }, { preset: "TIMER_5", target: { type: EffectScope.GEM, gemIndex: 7 } }, { preset: "CORRUPTION_1", target: { type: EffectScope.GEM, gemIndex: 8 } }]),
  [EffectPlaygroundScenario.GEM_EFFECT_COMBINATIONS]: level(EffectPlaygroundScenario.GEM_EFFECT_COMBINATIONS, [8, -6, 4, -5, 7, 3, -4, 5], [-2, 2, -2, 2, -3, -1, 1, -1], [{ preset: "SHIELD_2", target: { type: EffectScope.GEM, gemIndex: 0 } }, { preset: "MIRROR_1", target: { type: EffectScope.GEM, gemIndex: 0 } }, { preset: "SHIELD_2", target: { type: EffectScope.GEM, gemIndex: 1 } }, { preset: "AMPLIFIER_X2", target: { type: EffectScope.GEM, gemIndex: 1 } }, { preset: "MIRROR_1", target: { type: EffectScope.GEM, gemIndex: 2 } }, { preset: "AMPLIFIER_X2", target: { type: EffectScope.GEM, gemIndex: 2 } }, { preset: "SHIELD_2", target: { type: EffectScope.GEM, gemIndex: 3 } }, { preset: "MIRROR_1", target: { type: EffectScope.GEM, gemIndex: 3 } }, { preset: "AMPLIFIER_X2", target: { type: EffectScope.GEM, gemIndex: 3 } }, { preset: "INVERTER_1", target: { type: EffectScope.GEM, gemIndex: 4 } }, { preset: "SHIELD_2", target: { type: EffectScope.GEM, gemIndex: 4 } }]),
  [EffectPlaygroundScenario.WALL_WITH_FOLLOW_UP_EFFECTS]: level(EffectPlaygroundScenario.WALL_WITH_FOLLOW_UP_EFFECTS, [8, 5, 5, 5], [-2, -1, -1, -1], [{ preset: "WALL_1", target: { type: EffectScope.GEM, gemIndex: 0 } }, { preset: "MIRROR_1", target: { type: EffectScope.GEM, gemIndex: 0 } }, { preset: "AMPLIFIER_X2", target: { type: EffectScope.GEM, gemIndex: 0 } }, { preset: "INVERTER_1", target: { type: EffectScope.GEM, gemIndex: 0 } }]),
  [EffectPlaygroundScenario.LINK_EFFECTS]: level(EffectPlaygroundScenario.LINK_EFFECTS, [6, 6, 6, 6, 5, 4], [-2, -2, -2, -2, -1, -1], [{ preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 1 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "DOUBLE_LINK", target: { type: EffectScope.LINK, fromGemIndex: 1, toGemIndex: 2 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "INVERT_LINK", target: { type: EffectScope.LINK, fromGemIndex: 2, toGemIndex: 3 }, overrides: { direction: LinkDirection.BIDIRECTIONAL } }]),
  [EffectPlaygroundScenario.CHAIN_LOCK]: level(EffectPlaygroundScenario.CHAIN_LOCK, [2, 4, 4, 4], [-2, -2, -2, -2], [{ preset: "CHAIN_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 1 } }]),
  [EffectPlaygroundScenario.CHAIN_WITH_AREA]: level(EffectPlaygroundScenario.CHAIN_WITH_AREA, [2, 4, 5, 5, 5, 5], [-2, -2, -1, -1, -1, -1], [{ preset: "CHAIN_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 1 } }, { preset: "BOMB_2", target: { type: EffectScope.AREA, sourceGemIndex: 0 } }, { preset: "FIRE_1", target: { type: EffectScope.GEM, gemIndex: 2 } }]),
  [EffectPlaygroundScenario.LINK_GEM_SEQUENCE]: level(EffectPlaygroundScenario.LINK_GEM_SEQUENCE, [6, 9, 5, -7, 8], [-2, -1, -1, 2, -2], [{ preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 1 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "DOUBLE_LINK", target: { type: EffectScope.LINK, fromGemIndex: 1, toGemIndex: 2 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "INVERT_LINK", target: { type: EffectScope.LINK, fromGemIndex: 2, toGemIndex: 3 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 3, toGemIndex: 4 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "SHIELD_1", target: { type: EffectScope.GEM, gemIndex: 1 } }, { preset: "MIRROR_1", target: { type: EffectScope.GEM, gemIndex: 2 } }, { preset: "AMPLIFIER_X2", target: { type: EffectScope.GEM, gemIndex: 3 } }, { preset: "INVERTER_1", target: { type: EffectScope.GEM, gemIndex: 4 } }]),
  [EffectPlaygroundScenario.LINK_AREA_SEQUENCE]: level(EffectPlaygroundScenario.LINK_AREA_SEQUENCE, [4, 7, 6, -5, 8, 5], ["zero", -1, -2, "zero", -1, 1], [{ preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 1 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "DOUBLE_LINK", target: { type: EffectScope.LINK, fromGemIndex: 1, toGemIndex: 2 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "BOMB_2", target: { type: EffectScope.AREA, sourceGemIndex: 0 } }, { preset: "AREA_INVERTER_ALL", target: { type: EffectScope.AREA, sourceGemIndex: 3 } }, { preset: "SHIELD_1", target: { type: EffectScope.GEM, gemIndex: 1 } }, { preset: "MIRROR_1", target: { type: EffectScope.GEM, gemIndex: 2 } }]),
  [EffectPlaygroundScenario.LINK_MIXED_CASCADE]: level(EffectPlaygroundScenario.LINK_MIXED_CASCADE, [7, 5, 6, -4, 8, 3, 9], [-2, -1, "zero", 1, -2, -1, 1], [{ preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 1 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "DOUBLE_LINK", target: { type: EffectScope.LINK, fromGemIndex: 1, toGemIndex: 2 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "INVERT_LINK", target: { type: EffectScope.LINK, fromGemIndex: 2, toGemIndex: 3 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "CHAIN_LINK", target: { type: EffectScope.LINK, fromGemIndex: 3, toGemIndex: 4 } }, { preset: "BOMB_2", target: { type: EffectScope.AREA, sourceGemIndex: 2 } }, { preset: "WALL_1", target: { type: EffectScope.GEM, gemIndex: 1 } }, { preset: "MIRROR_1", target: { type: EffectScope.GEM, gemIndex: 3 } }, { preset: "AMPLIFIER_X2", target: { type: EffectScope.GEM, gemIndex: 4 } }, { preset: "INVERTER_1", target: { type: EffectScope.GEM, gemIndex: 5 } }]),
  [EffectPlaygroundScenario.AREA_EFFECTS]: level(EffectPlaygroundScenario.AREA_EFFECTS, [5, 5, 2, 5, 5, 5], [-1, -1, -2, -1, -1, -1], [{ preset: "BOMB_2", target: { type: EffectScope.AREA, sourceGemIndex: 2 } }]),
  [EffectPlaygroundScenario.ALL_AREA_EFFECTS]: level(EffectPlaygroundScenario.ALL_AREA_EFFECTS, [2, 5, 2, 5, 2, 5, 5, 5], [-2, -1, -2, -1, -2, -1, -1, -1], [{ preset: "AREA_BOMB_MINUS_2", target: { type: EffectScope.AREA, sourceGemIndex: 0 } }, { preset: "AREA_ICE_TWO_ADJACENT", target: { type: EffectScope.AREA, sourceGemIndex: 2 } }, { preset: "AREA_INVERTER_ALL", target: { type: EffectScope.AREA, sourceGemIndex: 4 } }]),
  [EffectPlaygroundScenario.FLOW_BRANCHING]: level(EffectPlaygroundScenario.FLOW_BRANCHING, [4, 5, 5, 5, 5, 5], [-2, -1, -1, -1, -1, -1], [{ preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 1 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 2 }, overrides: { direction: LinkDirection.FORWARD } }]),
  [EffectPlaygroundScenario.FLOW_CONVERGENCE]: level(EffectPlaygroundScenario.FLOW_CONVERGENCE, [4, 5, 5, 8, 5, 5], [-2, -1, -1, -1, -1, -1], [{ preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 1 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 2 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 1, toGemIndex: 3 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 2, toGemIndex: 3 }, overrides: { direction: LinkDirection.FORWARD } }]),
  [EffectPlaygroundScenario.FLOW_CYCLE]: level(EffectPlaygroundScenario.FLOW_CYCLE, [4, 5, 5, 5, 5, 5], [-2, -1, -1, -1, -1, -1], [{ preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 1 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 1, toGemIndex: 2 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 2, toGemIndex: 0 }, overrides: { direction: LinkDirection.FORWARD } }], { maxDepth: 3, allowMultipleIncomingFlows: true, combineStrategy: FlowCombineStrategy.SUM }),
  [EffectPlaygroundScenario.ALL_EFFECTS]: level(EffectPlaygroundScenario.ALL_EFFECTS, [4, 6, 6, 6, 2, 5, 5], [-2, -1, -1, -1, -2, -1, -1], [{ preset: "SHIELD_2", target: { type: EffectScope.GEM, gemIndex: 0 } }, { preset: "WALL_3", target: { type: EffectScope.GEM, gemIndex: 1 } }, { preset: "MIRROR_1", target: { type: EffectScope.GEM, gemIndex: 2 } }, { preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 1 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "DOUBLE_LINK", target: { type: EffectScope.LINK, fromGemIndex: 1, toGemIndex: 2 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "INVERT_LINK", target: { type: EffectScope.LINK, fromGemIndex: 2, toGemIndex: 3 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "BOMB_2", target: { type: EffectScope.AREA, sourceGemIndex: 4 } }]),
};
export const EFFECT_PLAYGROUND_ORDER = Object.values(EffectPlaygroundScenario);
export const EFFECT_PLAYGROUND_GROUP_ORDER = Object.values(EffectPlaygroundGroup);
export const EFFECT_PLAYGROUND_GROUP_LABEL: Readonly<Record<EffectPlaygroundGroup, string>> = {
  [EffectPlaygroundGroup.GEM]: "GEMME",
  [EffectPlaygroundGroup.LINK]: "LINK",
  [EffectPlaygroundGroup.AREA]: "AREA",
  [EffectPlaygroundGroup.FLOW]: "FLUSSI",
  [EffectPlaygroundGroup.COMPLETE]: "COMPLETO",
};
/** Second selector in the playground: focused cases first, then interactions with the other systems. */
export const EFFECT_PLAYGROUND_GROUP_SCENARIOS: Readonly<Record<EffectPlaygroundGroup, readonly EffectPlaygroundScenario[]>> = {
  [EffectPlaygroundGroup.GEM]: [EffectPlaygroundScenario.GEM_EFFECTS, EffectPlaygroundScenario.ALL_GEM_EFFECTS, EffectPlaygroundScenario.GEM_EFFECT_COMBINATIONS, EffectPlaygroundScenario.ELEMENTAL_BARRIERS, EffectPlaygroundScenario.WALL_WITH_FOLLOW_UP_EFFECTS],
  [EffectPlaygroundGroup.LINK]: [EffectPlaygroundScenario.LINK_EFFECTS, EffectPlaygroundScenario.CHAIN_LOCK, EffectPlaygroundScenario.CHAIN_WITH_AREA, EffectPlaygroundScenario.LINK_GEM_SEQUENCE, EffectPlaygroundScenario.LINK_AREA_SEQUENCE, EffectPlaygroundScenario.LINK_MIXED_CASCADE],
  [EffectPlaygroundGroup.AREA]: [EffectPlaygroundScenario.AREA_EFFECTS, EffectPlaygroundScenario.ALL_AREA_EFFECTS, EffectPlaygroundScenario.CHAIN_WITH_AREA],
  [EffectPlaygroundGroup.FLOW]: [EffectPlaygroundScenario.FLOW_BRANCHING, EffectPlaygroundScenario.FLOW_CONVERGENCE, EffectPlaygroundScenario.FLOW_CYCLE],
  [EffectPlaygroundGroup.COMPLETE]: [EffectPlaygroundScenario.ALL_EFFECTS],
};
