import { AreaEffectRange, AreaEffectType, EffectConfig, EffectScope, GemEffectType, LinkDirection, LinkEffectType, TimerUnit } from "./effects.models";

/** Central catalogue: levels only reference these stable names. */
export const EFFECT_PRESETS = {
  SHIELD_1: { scope: EffectScope.GEM, type: GemEffectType.SHIELD, strength: 1 },
  SHIELD_2: { scope: EffectScope.GEM, type: GemEffectType.SHIELD, strength: 2 },
  SHIELD_3: { scope: EffectScope.GEM, type: GemEffectType.SHIELD, strength: 3 },
  WALL_1: { scope: EffectScope.GEM, type: GemEffectType.WALL, strength: 1 },
  WALL_2: { scope: EffectScope.GEM, type: GemEffectType.WALL, strength: 2 },
  WALL_3: { scope: EffectScope.GEM, type: GemEffectType.WALL, strength: 3 },
  WALL_4: { scope: EffectScope.GEM, type: GemEffectType.WALL, strength: 4 },
  MIRROR_1: { scope: EffectScope.GEM, type: GemEffectType.MIRROR },
  AMPLIFIER_X2: { scope: EffectScope.GEM, type: GemEffectType.AMPLIFIER, multiplier: 2 },
  AMPLIFIER_X3: { scope: EffectScope.GEM, type: GemEffectType.AMPLIFIER, multiplier: 3 },
  INVERTER_1: { scope: EffectScope.GEM, type: GemEffectType.INVERTER },
  ICE_1: { scope: EffectScope.GEM, type: GemEffectType.ICE, strength: 1 },
  ICE_2: { scope: EffectScope.GEM, type: GemEffectType.ICE, strength: 2 },
  ICE_3: { scope: EffectScope.GEM, type: GemEffectType.ICE, strength: 3 },
  FIRE_1: { scope: EffectScope.GEM, type: GemEffectType.FIRE, strength: 1 },
  FIRE_2: { scope: EffectScope.GEM, type: GemEffectType.FIRE, strength: 2 },
  FIRE_3: { scope: EffectScope.GEM, type: GemEffectType.FIRE, strength: 3 },
  TIMER_3: { scope: EffectScope.GEM, type: GemEffectType.TIMER, turns: 3, unit: TimerUnit.IMPULSES },
  TIMER_5: { scope: EffectScope.GEM, type: GemEffectType.TIMER, turns: 5, unit: TimerUnit.IMPULSES },
  TIMER_7: { scope: EffectScope.GEM, type: GemEffectType.TIMER, turns: 7, unit: TimerUnit.IMPULSES },
  TIMER_10: { scope: EffectScope.GEM, type: GemEffectType.TIMER, turns: 10, unit: TimerUnit.IMPULSES },
  CORRUPTION_1: { scope: EffectScope.GEM, type: GemEffectType.CORRUPTION, amount: 1 },
  CORRUPTION_2: { scope: EffectScope.GEM, type: GemEffectType.CORRUPTION, amount: 2 },
  ECHO_LINK: { scope: EffectScope.LINK, type: LinkEffectType.ECHO },
  DOUBLE_LINK: { scope: EffectScope.LINK, type: LinkEffectType.AMPLIFY, multiplier: 2 },
  INVERT_LINK: { scope: EffectScope.LINK, type: LinkEffectType.INVERT },
  CHAIN_LINK: { scope: EffectScope.LINK, type: LinkEffectType.CHAIN, direction: LinkDirection.FORWARD },
  BOMB_1: { scope: EffectScope.AREA, type: AreaEffectType.BOMB, strength: 1, radius: 1 },
  BOMB_2: { scope: EffectScope.AREA, type: AreaEffectType.BOMB, strength: 2, radius: 1 },
  AREA_BOMB_MINUS_2: { scope: EffectScope.AREA, type: AreaEffectType.BOMB, value: -2, range: AreaEffectRange.ADJACENT },
  AREA_BOMB_PLUS_2: { scope: EffectScope.AREA, type: AreaEffectType.BOMB, value: 2, range: AreaEffectRange.ADJACENT },
  AREA_BOMB_MINUS_4: { scope: EffectScope.AREA, type: AreaEffectType.BOMB, value: -4, range: AreaEffectRange.TWO_ADJACENT },
  AREA_BOMB_PLUS_4: { scope: EffectScope.AREA, type: AreaEffectType.BOMB, value: 4, range: AreaEffectRange.TWO_ADJACENT },
  AREA_BOMB_MINUS_7: { scope: EffectScope.AREA, type: AreaEffectType.BOMB, value: -7, range: AreaEffectRange.ALL },
  AREA_BOMB_PLUS_7: { scope: EffectScope.AREA, type: AreaEffectType.BOMB, value: 7, range: AreaEffectRange.ALL },
  AREA_ICE_ADJACENT: { scope: EffectScope.AREA, type: AreaEffectType.ICE, strength: 1, range: AreaEffectRange.ADJACENT },
  AREA_ICE_TWO_ADJACENT: { scope: EffectScope.AREA, type: AreaEffectType.ICE, strength: 1, range: AreaEffectRange.TWO_ADJACENT },
  AREA_ICE_ALL: { scope: EffectScope.AREA, type: AreaEffectType.ICE, strength: 1, range: AreaEffectRange.ALL },
  AREA_INVERTER_ADJACENT: { scope: EffectScope.AREA, type: AreaEffectType.INVERTER, range: AreaEffectRange.ADJACENT },
  AREA_INVERTER_TWO_ADJACENT: { scope: EffectScope.AREA, type: AreaEffectType.INVERTER, range: AreaEffectRange.TWO_ADJACENT },
  AREA_INVERTER_ALL: { scope: EffectScope.AREA, type: AreaEffectType.INVERTER, range: AreaEffectRange.ALL },
} satisfies Record<string, EffectConfig>;

export type EffectPresetKey = keyof typeof EFFECT_PRESETS;
