/** Presentation-only tuning for all flows and effects. */
export const EFFECT_PHASER_VISUAL = {
  /** Green conduits from the gear to gems whose operation is currently usable. */
  activeFlows: {
    color: 0x59e77c,
    coreTrailColor: 0x8fffb0,
    coreColor: 0xf3fff6,
    alpha: 0.95,
    widthMultiplier: 1.48,
    particleCount: 3,
    particleStaggerMs: 390,
    glowPulseDurationMs: 1050,
    glowTraceAlphaMultiplier: 0.15,
    glowInitialAlpha: 0.28,
    glowPeakAlpha: 0.92,
    haloRadius: 10,
    haloAlphaMultiplier: 0.12,
    haloFadeAlphaMultiplier: 0.3,
    haloMinScale: 0.75,
    haloScaleRange: 0.9,
    particleRadius: 4.6,
    particleStrokeWidth: 2,
    particleMinScale: 0.72,
    particleScaleRange: 0.75,
    intensityBase: 0.35,
    intensityRange: 0.65,
    directPathRatio: 0.72,
    /** Link continuation uses the same three-layer active-flow treatment, sized from its gem radius. */
    linkGlowWidthRadiusRatio: 1.3,
    linkMiddleWidthRadiusRatio: 0.78,
    linkCoreWidthRadiusRatio: 0.25,
    linkGlowAlpha: 0.15,
    linkMiddleAlpha: 0.22,
    linkCoreAlpha: 0.72,
    linkTargetRingRadiusRatio: 1.48,
    durationMs: 1450,
    repeatDelayMs: 250,
  },
  /** Yellow topology previews for the operation that follows the active one. */
  yellowFlows: {
    color: 0xf3ce55,
    coreColor: 0xf3fff6,
    alpha: 0.78,
    widthMultiplier: 1,
    particleCount: 1,
    particleStaggerMs: 390,
    glowPulseDurationMs: 1050,
    glowTraceAlphaMultiplier: 0.15,
    glowInitialAlpha: 0.28,
    glowPeakAlpha: 0.92,
    haloRadius: 10,
    haloAlphaMultiplier: 0.12,
    haloFadeAlphaMultiplier: 0.3,
    haloMinScale: 0.75,
    haloScaleRange: 0.9,
    particleRadius: 2.6,
    particleStrokeWidth: 2,
    particleMinScale: 0.72,
    particleScaleRange: 0.75,
    intensityBase: 0.35,
    intensityRange: 0.65,
    directPathRatio: 0.72,
    durationMs: 1450,
    repeatDelayMs: 250,
  },
  /** Gray section of a blocked active flow, after it leaves the gear. */
  blockedFlows: { color: 0x929292, alpha: 0.76, widthMultiplier: 1.48 },
  /** Static effect links, their moving particles, and their active green continuation. */
  links: {
    alpha: 0.72,
    width: 3,
    outerGlowWidthExtra: 8,
    middleGlowWidthExtra: 4,
    outerGlowAlpha: 0.12,
    middleGlowAlpha: 0.28,
    coreAlpha: 0.9,
    particleRadius: 3.5,
    particleAlpha: 0.95,
    particleDurationMs: 1320,
    particleRepeatDelayMs: 220,
    particleMinScale: 0.7,
    particleScaleRange: 0.75,
    particleMinAlpha: 0.2,
    particleAlphaRange: 0.78,
    propagationParticleColor: 0xf5e58a,
    propagationParticleRadius: 2.8,
    propagationParticleAlpha: 0.98,
    propagationParticleScale: 1.35,
    propagationDurationMs: 620,
    propagationParticleCount: 3,
    propagationParticleStaggerMs: 90,
    propagationStageDelayMs: 260,
    propagationTrailColor: 0xffd568,
    propagationTrailWidth: 4,
    propagationTrailGlowWidthExtra: 6,
    propagationTrailAlpha: 0.9,
    activeColor: 0x62e98a,
    activeWidth: 4,
    activeGlowWidthExtra: 5,
    activeAlpha: 0.9,
    activeDurationMs: 680,
  },
  /**
   * One-shot current released by the central impulse.  It is deliberately
   * independent from the ambient green/yellow flow so its density and rhythm
   * can be tuned without changing the board's readable state.
   */
  impulseDischarge: {
    /** Bright white core used by every particle tail. */
    color: 0xffffff,
    particleStrokeColor: 0xffffff,
    haloColor: 0x59e77c,
    /** Number of complete particle tails.  `1` preserves the original single-tail discharge. */
    tailCount: 3,
    /** Angular offset between tails; 2π/3 makes the default three tails interlace evenly. */
    tailPhaseSpread: Math.PI * 2 / 3,
    particleCount: 14,
    particleRadius: 2.6,
    particleAlpha: 0.94,
    particleStrokeWidth: 1,
    particleStaggerMs: 34,
    particleMinScale: 0.5,
    particleScaleRange: 0.88,
    /** Direct trip from the impulse to the first active gems. */
    directDurationMs: 560,
    /** Duration of each curved link segment after the first gem. */
    linkSegmentDurationMs: 500,
    /** Delay between generations of a propagated effect chain. */
    linkGenerationDelayMs: 560,
    /** Side-to-side movement that makes the particles look intertwined. */
    weaveAmplitude: 11,
    weaveTurns: 2.4,
    phaseSpread: 0.7,
    haloRadius: 7,
    haloAlpha: 0.24,
    haloMinScale: 0.68,
    haloScaleRange: 0.9,
    arrivalBurstCount: 8,
    arrivalBurstDistance: 24,
    arrivalBurstDurationMs: 280,
    /** Numeric applied value shown at the exact arrival point of the discharge. */
    valueFloatDurationMs: 920,
    valueFloatRise: 52,
    valueFloatColor: 0xc5ffe0,
    depth: 22,
  },
  gemHighlightDuration: 190,
  wallBreakDuration: 330,
  bombDuration: 360,
  linkDepth: 3,
  gemDepth: 8,
  flowDepth: 15,
  hudActiveEffectPulseScale: 0.1,
  hudActiveEffectPulseDurationMs: 900,
} as const;
