import { PersistentLevelDefinition } from "../puzzle.types";
import { EffectScope, FlowCombineStrategy, LinkDirection } from "./effects.models";

export enum EffectPlaygroundScenario { GEM_EFFECTS = "GEM_EFFECTS", ALL_GEM_EFFECTS = "ALL_GEM_EFFECTS", GEM_EFFECT_COMBINATIONS = "GEM_EFFECT_COMBINATIONS", LINK_EFFECTS = "LINK_EFFECTS", AREA_EFFECTS = "AREA_EFFECTS", FLOW_BRANCHING = "FLOW_BRANCHING", FLOW_CONVERGENCE = "FLOW_CONVERGENCE", FLOW_CYCLE = "FLOW_CYCLE", ALL_EFFECTS = "ALL_EFFECTS" }
const level = (scenario: EffectPlaygroundScenario, outerValues: number[], innerValues: number[], effects: NonNullable<PersistentLevelDefinition["effectConfiguration"]>["effects"], flowRules?: NonNullable<PersistentLevelDefinition["effectConfiguration"]>["flowRules"]): PersistentLevelDefinition => ({ id: `effect-playground-${scenario.toLowerCase()}`, number: 1, title: `Effect Playground · ${scenario}`, schemaVersion: 1, variant: "persistent", positions: outerValues.length, initialRotation: 0, outerValues, innerValues, slotPhases: outerValues.map((_, outerIndex) => [{ outerIndex }]), effectConfiguration: { enabled: true, effects, flowRules } });

export const EFFECT_PLAYGROUND_SCENARIOS: Readonly<Record<EffectPlaygroundScenario, PersistentLevelDefinition>> = {
  [EffectPlaygroundScenario.GEM_EFFECTS]: level(EffectPlaygroundScenario.GEM_EFFECTS, [8, -6, 4, -8, 5, -3], [-2, 2, -2, 2, -1, 1], [{ preset: "SHIELD_2", target: { type: EffectScope.GEM, gemIndex: 0 } }, { preset: "WALL_3", target: { type: EffectScope.GEM, gemIndex: 1 } }, { preset: "MIRROR_1", target: { type: EffectScope.GEM, gemIndex: 2 } }]),
  [EffectPlaygroundScenario.ALL_GEM_EFFECTS]: level(EffectPlaygroundScenario.ALL_GEM_EFFECTS, [8, -6, 4, -5, 7, -8, 3, -4], [-2, 2, -2, 2, -2, 2, -1, 1], [{ preset: "SHIELD_2", target: { type: EffectScope.GEM, gemIndex: 0 } }, { preset: "WALL_3", target: { type: EffectScope.GEM, gemIndex: 1 } }, { preset: "MIRROR_1", target: { type: EffectScope.GEM, gemIndex: 2 } }, { preset: "AMPLIFIER_X2", target: { type: EffectScope.GEM, gemIndex: 3 } }, { preset: "INVERTER_1", target: { type: EffectScope.GEM, gemIndex: 4 } }, { preset: "ICE_2", target: { type: EffectScope.GEM, gemIndex: 5 } }, { preset: "TIMER_5", target: { type: EffectScope.GEM, gemIndex: 6 } }, { preset: "CORRUPTION_1", target: { type: EffectScope.GEM, gemIndex: 7 } }]),
  [EffectPlaygroundScenario.GEM_EFFECT_COMBINATIONS]: level(EffectPlaygroundScenario.GEM_EFFECT_COMBINATIONS, [8, -6, 4, -5, 7, 3, -4, 5], [-2, 2, -2, 2, -2, -1, 1, -1], [{ preset: "SHIELD_2", target: { type: EffectScope.GEM, gemIndex: 0 } }, { preset: "MIRROR_1", target: { type: EffectScope.GEM, gemIndex: 0 } }, { preset: "SHIELD_2", target: { type: EffectScope.GEM, gemIndex: 1 } }, { preset: "AMPLIFIER_X2", target: { type: EffectScope.GEM, gemIndex: 1 } }, { preset: "MIRROR_1", target: { type: EffectScope.GEM, gemIndex: 2 } }, { preset: "AMPLIFIER_X2", target: { type: EffectScope.GEM, gemIndex: 2 } }, { preset: "SHIELD_2", target: { type: EffectScope.GEM, gemIndex: 3 } }, { preset: "MIRROR_1", target: { type: EffectScope.GEM, gemIndex: 3 } }, { preset: "AMPLIFIER_X2", target: { type: EffectScope.GEM, gemIndex: 3 } }, { preset: "INVERTER_1", target: { type: EffectScope.GEM, gemIndex: 4 } }, { preset: "SHIELD_2", target: { type: EffectScope.GEM, gemIndex: 4 } }]),
  [EffectPlaygroundScenario.LINK_EFFECTS]: level(EffectPlaygroundScenario.LINK_EFFECTS, [6, 6, 6, 6, 5, 4], [-2, -2, -2, -2, -1, -1], [{ preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 1 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "DOUBLE_LINK", target: { type: EffectScope.LINK, fromGemIndex: 1, toGemIndex: 2 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "INVERT_LINK", target: { type: EffectScope.LINK, fromGemIndex: 2, toGemIndex: 3 }, overrides: { direction: LinkDirection.BIDIRECTIONAL } }]),
  [EffectPlaygroundScenario.AREA_EFFECTS]: level(EffectPlaygroundScenario.AREA_EFFECTS, [5, 5, 2, 5, 5, 5], [-1, -1, -2, -1, -1, -1], [{ preset: "BOMB_2", target: { type: EffectScope.AREA, sourceGemIndex: 2 } }]),
  [EffectPlaygroundScenario.FLOW_BRANCHING]: level(EffectPlaygroundScenario.FLOW_BRANCHING, [4, 5, 5, 5, 5, 5], [-2, -1, -1, -1, -1, -1], [{ preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 1 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 2 }, overrides: { direction: LinkDirection.FORWARD } }]),
  [EffectPlaygroundScenario.FLOW_CONVERGENCE]: level(EffectPlaygroundScenario.FLOW_CONVERGENCE, [4, 5, 5, 8, 5, 5], [-2, -1, -1, -1, -1, -1], [{ preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 1 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 2 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 1, toGemIndex: 3 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 2, toGemIndex: 3 }, overrides: { direction: LinkDirection.FORWARD } }]),
  [EffectPlaygroundScenario.FLOW_CYCLE]: level(EffectPlaygroundScenario.FLOW_CYCLE, [4, 5, 5, 5, 5, 5], [-2, -1, -1, -1, -1, -1], [{ preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 1 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 1, toGemIndex: 2 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 2, toGemIndex: 0 }, overrides: { direction: LinkDirection.FORWARD } }], { maxDepth: 3, allowMultipleIncomingFlows: true, combineStrategy: FlowCombineStrategy.SUM }),
  [EffectPlaygroundScenario.ALL_EFFECTS]: level(EffectPlaygroundScenario.ALL_EFFECTS, [4, 6, 6, 6, 2, 5, 5], [-2, -1, -1, -1, -2, -1, -1], [{ preset: "SHIELD_2", target: { type: EffectScope.GEM, gemIndex: 0 } }, { preset: "WALL_3", target: { type: EffectScope.GEM, gemIndex: 1 } }, { preset: "MIRROR_1", target: { type: EffectScope.GEM, gemIndex: 2 } }, { preset: "ECHO_LINK", target: { type: EffectScope.LINK, fromGemIndex: 0, toGemIndex: 1 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "DOUBLE_LINK", target: { type: EffectScope.LINK, fromGemIndex: 1, toGemIndex: 2 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "INVERT_LINK", target: { type: EffectScope.LINK, fromGemIndex: 2, toGemIndex: 3 }, overrides: { direction: LinkDirection.FORWARD } }, { preset: "BOMB_2", target: { type: EffectScope.AREA, sourceGemIndex: 4 } }]),
};
export const EFFECT_PLAYGROUND_ORDER = Object.values(EffectPlaygroundScenario);
